const names = {
    // Circles
    "**": "Random Circle",
    "*0": "Blue Circle",
    "*1": "Green Circle",
    "*2": "Orange Circle",
    "*3": "Purple Circle",
    "*4": "Red Circle",
    "*5": "Yellow Circle",
    "*B": "Black Circle",
    "*-": "Horizontal Striped Circle",
    "*|": "Vertical Striped Circle",
    "*O": "Radial Circle",
    "*+": "Extra Time Circle",
    "*/": "Rainbow Circle",
    "*K": "Key",
    // Blockers
    "M1": "1-Layered Metal Ball",
    "M2": "2-Layered Metal Ball",
    "M3": "3-Layered Metal Ball",
    "M4": "4-Layered Metal Ball",
    "M5": "5-Layered Metal Ball",
    "M6": "6-Layered Metal Ball",

    "W1": "1-Layered Watermelon",
    "W2": "2-Layered Watermelon",
    "W3": "3-Layered Watermelon",

    "J1": "1-Layered Jawbreaker (Gum)",
    "J2": "2-Layered Jawbreaker",
    "J3": "3-Layered Jawbreaker",
    "J4": "4-Layered Jawbreaker",

    "d1": "1-Layered Donut",
    "d2": "2-Layered Donut",
    "d3": "3-Layered Donut",

    "I0": "Ice",
    // Encasers
    "D1": "1-Layered Drain",
    "D2": "2-Layered Drain",
    "b1": "1-Layered Bubble",
    "b2": "2-Layered Bubble",
    "b3": "3-Layered Bubble",
    // Misc
    "--": "No Tile",
    "-O": "Empty Tile",
    "*S": "Spawn Point",
    "*s": "Only Select Tile",
    "-C": "Remove all Cannon Tiles",
    "-c": "Remove Camera",
    "B1": "1-Layered Button",
    "B2": "2-Layered Button",
    "B3": "3-Layered Button",
    "G1": "Globe",
    "G2": "Held Globe",
    "G-": "Globe Exit",
    "PT": "Paint Tile",
    "cp": "Camera",
    "c1": "1-Layered Circle Chest",
    "c2": "2-Layered Circle Chest",
    "c3": "3-Layered Circle Chest",
    "c4": "4-Layered Circle Chest",
    "c5": "5-Layered Circle Chest",
    // Cannons
    "CW": "Watermelon Cannon",
    "Cd": "Donut Cannon",
    "CJ": "Jawbreaker Cannon",
    "CG": "Globe Cannon",
    "C-": "Horizontal Striped Circle Cannon",
    "C|": "Vertical Striped Circle Cannon",
    "CO": "Radial Circle Cannon",
    "C+": "Extra Time Circle Cannon",
    "CK": "Key Cannon",
    /// Walls
    "-W": "Remove all Wall Tiles",
    // Beads
    "E^": "Beads (Up)",
    "E<": "Beads (Left)",
    "E>": "Beads (Right)",
    "Ev": "Beads (Down)",
    // Custom Spawn Points
    "S1": "Custom Spawn Point #1",
    "S2": "Custom Spawn Point #2",
    "S3": "Custom Spawn Point #3",
    "S4": "Custom Spawn Point #4",
    "S5": "Custom Spawn Point #5",
    "S6": "Custom Spawn Point #6",
    "S7": "Custom Spawn Point #7",
    "S8": "Custom Spawn Point #8",
    "S9": "Custom Spawn Point #9"
}

export default names;